language: node_js
node_js:
  - '7'
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
install: yarn install
script:
  - yarn build
notifications:
  email: false
